### PR TITLE
Prevent masking value variables with imports

### LINKED ISSUE #2: Local variables 'mask', 'offset' shadowed in macros
A variable named `mask` or `offset` is shadowed by the imports within the `modify_reg!` and `write_reg!` macros:

```rust
let mask = 6;
ral::write_reg!(self, &register_block, register, field_foo: mask);
```

This results in the following compiler warning:

```
warning: unused variable: `mask`
  --> tests/macros.rs:87:9
   |
87 |     let mask = 6;
   |         ^^^^ help: if this is intentional, prefix it with an underscore: `_mask`
```

### PR DESCRIPTION
**Pull request by Disasm**
Fixes #2

### CODE REVIEW

**Comment by mciantyre** [comment]
I'm having trouble cherry-picking this commit onto #3. I needed extra `{}` throughout, changing patterns like

```rust
{ use $periph::$reg::$field::offset; offset }
```

into

```rust
{ use $periph::{$reg::$field::offset}; offset }
```

Why is that?

**Comment by Disasm** [comment]
Hmm, interesting. I removed braces because they looked useless to me, but apparently they are required for something.

**Comment by Disasm** [comment]
Updated. Now it work with your tests.

**Comment by adamgreig** [comment]
It's a shame this update reduces the readability of the generated code, but it does nicely solve the shadowing of values, thanks! If it wasn't for https://github.com/rust-lang/rust/issues/48067 we could just write `$periph::$reg::$field::offset` directly without using it, but alas.

**Review by adamgreig — APPROVED** [review]

**Pull request merged**
